### ISSUE TITLE
Upgrading to newer `zemu` causes tests to fail which pass with older `zemu`

### ISSUE THREAD

**Issue by simonhf** [Zondax/zemu#84]
* Have been trying to upgrade an app from Ledger SDK 1.6 to 2.0.
* Managed to do this and build the app with SDK 2.0, which also works on the device, but...
* ...in order to run the (emulated) integration tests then `zemu` needs to be upgraded too, but...
* ...after upgrading `zemu` many integration tests fail (even though they all passed before).
* Looking at the first test which fails then the issue seems to be that `clickBoth()` is only causing a click right button.
* Here I present the sSteps to reproduce this `clickBoth()` issue with the newer `zemu` for the first failing test:
  * Note: I leave out the steps for upgrading to building with SDK 2.0, because the test fails in the same way when building the app with SDK 1.6 and testing with newer `zemu`.
* Clone app and build it:

```
$ git clone https://github.com/onflow/ledger-app-flow.git && cd ledger-app-flow
$ echo checkout specific commit for easier replication
$ git checkout 767ffe9d4c9641ea8196128a5e90c33dd3ce270a
$ git submodule update --init --recursive

$ make 2>&1 | tee ../build-with-older-zemu.log ; wc -c app/bin/app.elf
  593044 app/bin/app.elf
```

* Disable all `zemu` tests except the first test -- `slot status - set` -- which passes on older `zemu` but fails on newer `zemu`:

```
$ echo disable all transaction tests
$ mv tests_zemu/tests/transactions.spec.js tests_zemu/tests/transactions.spec.js.ignore

$ echo disable all basic tests except `slot status - set`
$ vim tests_zemu/tests/basic.spec.js
$ git diff tests_zemu/tests/basic.spec.js
git diff tests_zemu/tests/basic.spec.js
diff --git a/tests_zemu/tests/basic.spec.js b/tests_zemu/tests/basic.spec.js
index 7770afe..9f82ce3 100644
--- a/tests_zemu/tests/basic.spec.js
+++ b/tests_zemu/tests/basic.spec.js
@@ -21,6 +21,7 @@ import FlowApp from "@onflow/ledger";
 import { APP_PATH, simOptions, verifyAndAccept } from "./setup";
 
 describe("Basic checks", function () {
+/*
     test("can start and stop container", async function () {
         const sim = new Zemu(APP_PATH);
         try {
@@ -82,7 +83,7 @@ describe("Basic checks", function () {
     });
 
     // accounts
-
+*/
     test("slot status - set", async function () {
         const sim = new Zemu(APP_PATH);
         try {
@@ -110,7 +111,7 @@ describe("Basic checks", function () {
             await sim.close();
         }
     });
-
+/*
     test("slot status - update", async function () {
         const sim = new Zemu(APP_PATH);
         try {
@@ -419,4 +420,5 @@ describe("Basic checks", function () {
             await sim.close();
         }
     });
+*/
 });
```

* Enable extra verbosity during testing:

```
$ echo turn on extra verbosity during tests
$ vim tests_zemu/package.json
$ vim tests_zemu/tests/setup.js
$ git diff tests_zemu/package.json tests_zemu/tests/setup.js                         
diff --git a/tests_zemu/package.json b/tests_zemu/package.json
...
   "name": "integration-tests",
+  "jest": {
+    "verbose": true
+  },
...
   "scripts": {
-    "test": "jest --detectOpenHandles"
+    "test": "jest --verbose --detectOpenHandles"
...
diff --git a/tests_zemu/tests/setup.js b/tests_zemu/tests/setup.js
...
     // logging: true,
+    logging: true,
```

* Install `zemu` dependencies:

```
$ make zemu_install
```

* Run currently default older `zemu` in which test passes:

```
$ rm -rf tests_zemu/tests/__image_snapshots__/__diff_output__/ ; make zemu_test 2>&1 | tee ../test-with-older-zemu.log
...
$ jest --verbose --detectOpenHandles
***** Progress on image: zondax/builder-zemu@sha256:4b793ac77c29870e6046e1d0a5019643fd178530205f9cf983bfadd114abca0a *****
Pulling from zondax/builder-zemu 
 
***** Progress on image: zondax/builder-zemu@sha256:4b793ac77c29870e6046e1d0a5019643fd178530205f9cf983bfadd114abca0a *****
Digest: sha256:4b793ac77c29870e6046e1d0a5019643fd178530205f9cf983bfadd114abca0a 
 
***** Progress on image: zondax/builder-zemu@sha256:4b793ac77c29870e6046e1d0a5019643fd178530205f9cf983bfadd114abca0a *****
Status: Image is up to date for zondax/builder-zemu@sha256:4b793ac77c29870e6046e1d0a5019643fd178530205f9cf983bfadd114abca0a 
 
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
[ZEMU] Command: /home/zondax/speculos/speculos.py --color LAGOON_BLUE --display headless -s "equip will roof matter pink blind book anxiety banner elbow sun young" --vnc-port 8001 /project/app/bin/app.elf
[ZEMU] Connected e95270cd0296778f26d9cf9b92008db7a7788acd03a57e9f3076d41897a39dd1

--------------------------------------
Zemu container - zondax.ch
--------------------------------------

HTTP proxy started...
BOLOS_SDK=/project/deps/nanos-secure-sdk
BOLOS_ENV=/opt/bolos

serving at port 9998
[*] using SDK version 1.6
[*] patching svc instruction at 0x40002be8
[*] patching svc instruction at 0x4000ce3c
172.17.0.1 - - [01/Sep/2021 17:43:32] "GET / HTTP/1.1" 200 -
[ZEMU] VNC Connection created 127.0.0.1:8001
[ZEMU] VNC Session ready
  console.log ../js/dist/index.js:487
    <Buffer 0a>

  console.log ../js/dist/index.js:488
    <Buffer 00 01 02 03 04 05 06 07>

  console.log ../js/dist/index.js:489
    <Buffer 2c 00 00 80 1b 02 00 80 01 02 00 80 00 00 00 00 00 00 00 00>

  console.log ../js/dist/index.js:491
    <Buffer 0a 00 01 02 03 04 05 06 07 2c 00 00 80 1b 02 00 80 01 02 00 80 00 00 00 00 00 00 00 00>

< b'331200001d0a00010203040506072c0000801b020080010200800000000000000000'
17:43:32.460:apdu: > 331200001d0a00010203040506072c0000801b020080010200800000000000000000
17:43:35.362:apdu: < 9000
> b'9000'
172.17.0.1 - - [01/Sep/2021 17:43:35] "POST / HTTP/1.1" 200 -
  console.log tests/basic.spec.js:107
    { returnCode: 36864, errorMessage: 'No errors' }


[ZEMU] Stopping container
PASS tests/basic.spec.js
  Basic checks
    ✓ slot status - set (14247 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   5 passed, 5 total
Time:        15.91 s
Ran all test suites.
Done in 20.55s.
```

* Upgrade `package.json` so that never `zemu` gets used:

```
$ echo update integration test spec to use newer `zemu`
$ vim tests_zemu/package.json
$ git diff tests_zemu/package.json | egrep zemu
...
-    "@zondax/zemu": "^0.7.0"
+    "@zondax/zemu": "^0.16.5"
```

* Install `zemu` dependencies:

```
$ make zemu_install
```

* Determine SDK used and update emulator launcher to expect that SDK:

```
$ git submodule status
 e3293938e5988e1ffa05d1f2ba23db431275f21c deps/nanos-secure-sdk (nanos-161)
$ echo this is tag `nanos-161` from Aug 26, 2020
$ eche please see tags at https://github.com/LedgerHQ/nanos-secure-sdk/releases

$ echo emulator will default to SDK version 2.0, but tell it to use version 1.6:
$ cp tests_zemu/node_modules/@zondax/zemu/dist/emulator.js tests_zemu/node_modules/@zondax/zemu/dist/emulator.js.orig
$ diff tests_zemu/node_modules/@zondax/zemu/dist/emulator.js.orig tests_zemu/node_modules/@zondax/zemu/dist/emulator.js
172c172
<                         SDKoption = '';
---
>                         SDKoption = ' -k 1.6 ';
```

* Run newer `zemu` in which test fails:

```
$ rm -rf tests_zemu/tests/__image_snapshots__/__diff_output__/ ; make zemu_test 2>&1 | tee ../test-with-newer-zemu.log
...
$ jest --verbose --detectOpenHandles
[DOCKER] Pulling from zondax/builder-zemu: 
[DOCKER] Digest: sha256:fd969f588c9b5444c887397e19d00f4465bc87526428bc25a43adb6f6b2ba71c: 
[DOCKER] Status: Image is up to date for zondax/builder-zemu:0c7c0c2f6a23e8018dad1de53fa1b23a27a48f6e: 
[ZEMU] 18:16:09.345: Checking ELF
[ZEMU] 18:16:09.351: Starting Container
[ZEMU] Command: /home/zondax/speculos/speculos.py --log-level speculos:DEBUG --log-level vnc:DEBUG --log-level vnc:DEBUG --color JADE_GREEN --display headless -s "equip will roof matter pink blind book anxiety banner elbow sun young" -m nanos  -k 1.6  --vnc-port 8001 /project/app/bin/app.elf 
[ZEMU] Creating Container
[ZEMU] Connected 69b2c535bfc198ae3d0614f60c57a6be223709abcbec59105a6b44218b563684
[ZEMU] Attached 69b2c535bfc198ae3d0614f60c57a6be223709abcbec59105a6b44218b563684

--------------------------------------
Zemu container - zondax.ch
--------------------------------------

HTTP proxy started...
[ZEMU] Started 69b2c535bfc198ae3d0614f60c57a6be223709abcbec59105a6b44218b563684
[ZEMU] 18:16:11.730: Started Container
[ZEMU] 18:16:11.730: Wait VNC for 3500 ms
[ZEMU] 18:16:15.235: VNC Connection created 127.0.0.1:58496
BOLOS_SDK=/project/deps/nanos-secure-sdk
BOLOS_ENV=/opt/bolos

serving at port 9998
18:16:12.363:speculos: executing qemu: ['qemu-arm-static', '/home/zondax/speculos/build/src/launcher', '-m', 'nanos', '-k', '1.6', 'main:/project/app/bin/app.elf:0x10000:0x14800:0x20001800:0x1000']
 * Serving Flask app 'api.api' (lazy loading)
 * Environment: development
 * Debug mode: off
18:16:12.370:werkzeug:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
18:16:12.371:werkzeug:  * Running on http://172.17.0.2:5000/ (Press CTRL+C to quit)
[*] speculos launcher revision: 5b0b2c4
[*] using SDK version 1.6
[*] patching svc instruction at 0x40002be8
[*] patching svc instruction at 0x4000ce3c
[ZEMU] 18:16:15.356: VNC Session ready
172.17.0.1 - - [01/Sep/2021 18:16:15] "GET / HTTP/1.1" 200 -
[ZEMU] 18:16:15.378: Get initial snapshot
  console.log ../js/dist/index.js:487
    <Buffer 0a>

  console.log ../js/dist/index.js:488
    <Buffer 00 01 02 03 04 05 06 07>

  console.log ../js/dist/index.js:489
    <Buffer 2c 00 00 80 1b 02 00 80 01 02 00 80 00 00 00 00 00 00 00 00>

  console.log ../js/dist/index.js:491
    <Buffer 0a 00 01 02 03 04 05 06 07 2c 00 00 80 1b 02 00 80 01 02 00 80 00 00 00 00 00 00 00 00>

< b'331200001d0a00010203040506072c0000801b020080010200800000000000000000'
18:16:15.444:apdu: > 331200001d0a00010203040506072c0000801b020080010200800000000000000000
[ZEMU] 18:16:15.454: Wait for screen change
[ZEMU] 18:16:15.957: Check [14ms]
[ZEMU] 18:16:15.971: Screen changed
[ZEMU] 18:16:15.984: Wait for screen change
[ZEMU] 18:16:15.984: Screen changed
[ZEMU] 18:16:16.990: Click Right undefined
[ZEMU] 18:16:17.983: Click Right undefined
[ZEMU] 18:16:18.981: Click Right undefined
[ZEMU] 18:16:19.998: Click Both  undefined
[ZEMU] 18:16:20.708: Close
[ZEMU] Stopping container
FAIL tests/basic.spec.js
  Basic checks
    ✕ slot status - set (13527 ms)

  ● Basic checks › slot status - set

    Expected image to match or be a close match to snapshot but was 15.673828125% different from snapshot (642 differing pixels).
    See diff for details: /Users/simonhardy-francis/work/20210901-ledger-app-flow-legacy/ledger-app-flow/tests_zemu/tests/__image_snapshots__/__diff_output__/basic-spec-js-basic-checks-slot-status-set-5-diff.png

      102 |             // Now navigate the address / path
      103 |             const snapshots = await verifyAndAccept(sim, 3);
    > 104 |             snapshots.forEach((image) => expect(image).toMatchImageSnapshot());
          |                                                        ^
      105 |     
      106 |             const resp = await respRequest;
      107 |             console.log(resp);

      at forEach (tests/basic.spec.js:104:56)
          at Array.forEach (<anonymous>)
      at _callee$ (tests/basic.spec.js:104:23)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
      at Generator.next (node_modules/regenerator-runtime/runtime.js:118:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)

 › 1 snapshot failed.
Snapshot Summary
 › 1 snapshot failed from 1 test suite. Inspect your code changes or run `yarn test -u` to update them.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   1 failed, 5 passed, 6 total
Time:        14.71 s
Ran all test suites.
[ZEMU] Stopped
[ZEMU] Removed
error Command failed with exit code 1.
...
```

* Notice that the last part of the test involves a `clickBoth()` call which appears to fail, and instead only a click right seems to happen looking at the screen shot diff:
  * Note: The `clickBoth()` function is located here: https://github.com/Zondax/zemu/blob/master/src/index.ts#L472

```
$ find tests_zemu -type f | egrep "__diff_output__"                                                                   
tests_zemu/tests/__image_snapshots__/__diff_output__/basic-spec-js-basic-checks-slot-status-set-5-diff.png
$ open tests_zemu/tests/__image_snapshots__/__diff_output__/basic-spec-js-basic-checks-slot-status-set-5-diff.png
```

![basic-spec-js-basic-checks-slot-status-set-5-diff](https://user-images.githubusercontent.com/357158/131727780-69d43cde-9296-4c63-ad69-0fabd1a26666.png)

* I'm guessing `clickBoth()` is using the emulator VNC connection to send both button presses and releases to the emulator?
* Why does is `clickBoth()` failing with newer `zemu` and how to fix it?

**Comment by jleni** [comment]
A side effect of upgrading Zemu is that it will include a fix in the emulation layer.
In the past, there was a missing pixel in the right arrow. This was part of a fix in speculos and affects a large amount of the images that are now generated.

With respect to clicks, we have not detected any issue in `clickBoth()` in any of the apps we maintain. However, at the moment, there is a debouncing time that is required due to the lack of a repaint callback. If the machine where you are running is very slow, maybe there is a difference in the timing but this is not a logical problem in the new code as far as we know.

**Comment by jleni** [comment]
Still, if you find a way to reproduce this issue in our Zemu unit/integration tests, we would be glad to investigate deeper and address it! We are more than glad to accept contributions!!

**Comment by simonhf** [comment]
> In the past, there was a missing pixel in the right arrow.

Thanks for the comment. Good to know, but I don't think this is the issue, otherwise presumably the image diff would have flagged an earlier screen shot and not got this far in the test?

> If the machine where you are running is very slow, maybe there is a difference in the timing but this is not a logical problem in the new code as far as we know.

Thanks for the comment. The machine is a 2022 MacBook Pro with Activity Monitor constantly running to ensure that no unwanted processes are running in the background :-) So hopefully we can rule out a slow machine. And also please don't forget that this machine has also run the tests many times successfully with the older `zemu`.

> find a way to reproduce this issue in our Zemu unit/integration tests

Thanks for the comment. I was originally looking for the Zemu unit/integration tests but could find them or instructions to run them. So I did the next best thing which is to reproduce the issue with an existing open source project with detailed instructions to reproduce. @jleni, can you please point me towards the Zemu unit/integration tests and how to run them? Thanks! :-)

**Comment by simonhf** [comment]
@jleni I managed to figure out how to run the Zemu unit/integration tests, and below are the instructions I used on MacOS (had to install some typescript stuff to make it run). All the tests passed for me which is good news. I saw that `cilckBoth()` is used twice in the tests, and now looking into how it is tested, and what the differences are to my scenario :-)

```
$ git clone https://github.com/Zondax/zemu.git && cd zemu
$ cd tests && yarn --verbose test
...
$ tsc && yarn copy-files
/bin/sh: tsc: command not found
```

* Install typescript:

```
$ brew install typescript
$ tsc --version
Version 4.4.2
```

* Run tests again:

```
$ cd tests && yarn --verbose test
cd tests && yarn --verbose test
yarn run v1.22.11
...
$ yarn build && jest
$ tsc && yarn copy-files
error TS2468: Cannot find global value 'Promise'.

src/emulator.ts:16:14 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

16 const path = require('path')
                ~~~~~~~

src/emulator.ts:17:16 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

17 const Docker = require('dockerode')
                  ~~~~~~~
...
Found 58 errors.
error Command failed with exit code 1.
```

* Try the command that the first error messages suggests:

```
$ npm i --save-dev @types/node
...
added 615 packages, and audited 616 packages in 43s
```

* Switch on extra verbosity for tests:

```
$ git diff package.json 
...
   "name": "@zondax/zemu",
+  "jest": {
+    "verbose": true
+  },
...
-    "test": "yarn build && jest"
+    "test": "yarn build && jest --verbose --detectOpenHandles"
...
```

* Run tests again:

```
$ pushd tests && yarn --verbose test 2>&1 | tee ../../yarn-tests.log ; popd
...
Test Suites: 2 passed, 2 total
Tests:       15 passed, 15 total
Snapshots:   0 total
Time:        117.796 s
Ran all test suites.
Executing clean up tasks after finishing all test suites
[ZEMU] Stopped
[ZEMU] Removed
Done in 127.86s.

$ cat ../yarn-tests.log | egrep -i "\b(pass|fail|click both)\b"

[ZEMU] 17:52:56.067: Click Both  /Users/simonhardy-francis/20210902-zemu/zemu/tests/snapshots-tmp/compare_test/00002.png
[ZEMU] 17:53:08.328: Click Both  /Users/simonhardy-francis/20210902-zemu/zemu/tests/snapshots-tmp/compare_test2/00004.png
PASS tests/basic.s.test.ts (83.855 s)
PASS tests/basic.x.test.ts (33.859 s)
```

**Comment by simonhf** [comment]
@jleni I noticed that the Zemu unit/integration tests reference [1] a pre-compiled binary [2]. Could this `clickBoth()` issue be to do with how the binary app is built? If so, how is `demoAppS.elf` built? Is there a github repo for that (with build instructions?)?

[1] https://github.com/Zondax/zemu/blob/master/tests/basic.s.test.ts#L22
[2] https://github.com/Zondax/zemu/blob/master/bin/demoAppS.elf

**Comment by jleni** [comment]
We are progressively adding support for some new speculos features
